---
linters:
  enable:
    - revive
    - sloglint

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

linters-settings:
  errcheck:
    exclude-functions: scripts/errcheck_excludes.txt
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: true
