go:
    # This must match .circle/config.yml.
    version: 1.16
repository:
    path: github.com/prometheus-community/elasticsearch_exporter
build:
    binaries:
        - name: elasticsearch_exporter
    flags: -a -tags netgo
    ldflags: |
        -s
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - README.md
        - CHANGELOG.md
        - examples/grafana/dashboard.json
        - examples/kubernetes/deployment.yml
        - examples/prometheus/elasticsearch.rules
