FROM golang:1.25 AS builder

ARG TARGETOS=linux
ARG TARGETARCH=amd64

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags "-s -w" -o /elasticsearch_exporter .

FROM gcr.io/distroless/static-debian12:nonroot
LABEL io.prometheus.image.variant="ghcr"
COPY --from=builder /elasticsearch_exporter /bin/elasticsearch_exporter
EXPOSE 9114
USER nonroot
ENTRYPOINT ["/bin/elasticsearch_exporter"]
