{
 "title": "Elasticsearch Exporter /  Cluster",
 "tags": [ "elasticsearch-exporter-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_active_shards{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  {
   "title": "Active Primary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  {
   "title": "Initializing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_initializing_shards{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  {
   "title": "Relocating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_relocating_shards{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  {
   "title": "Unassigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_unassigned_shards{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  {
   "title": "DelayedUnassigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n  elasticsearch_cluster_health_delayed_unassigned_shards{cluster=~\"$cluster\"}\n)\n"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Indexed Documents",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{cluster=~\"$cluster\"}\n"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes{cluster=~\"$cluster\"}\n"
    }
   ]
  },
  {
   "title": "Index Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=~\"$cluster\"}[$__rate_interval])\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{cluster=~\"$cluster\"}[$__rate_interval])\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(elasticsearch_thread_pool_queue_count{cluster=~\"$cluster\",type!=\"management\"}) by (type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{cluster=~\"$cluster\"}\n",
     "legendFormat": "{{name}} {{area}}"
    }
   ]
  },
  {
   "title": "Memory 15m Avg",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(\n  elasticsearch_jvm_memory_used_bytes{cluster=~\"$cluster\"}[15m]\n) /\nelasticsearch_jvm_memory_max_bytes{cluster=~\"$cluster\"}\n",
     "legendFormat": "{{name}} {{area}}"
    }
   ]
  },
  {
   "title": "Memory Max",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{cluster=~\"$cluster\"}\n",
     "legendFormat": "{{name}} {{area}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(\n  elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\"}[$__rate_interval]\n)\n",
     "legendFormat": "{{name}} {{gc}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Thread Pools",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{cluster=~\"$cluster\"}\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Thread Pool Rejections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_rejected_count{cluster=~\"$cluster\"}\n",
     "legendFormat": "{{name}} {{type}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Transport Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(\n  elasticsearch_transport_rx_size_bytes_total{cluster=~\"$cluster\"}[$__rate_interval]\n)\n",
     "legendFormat": "{{name}} TX"
    },
    {
     "expr": "rate(\n  elasticsearch_transport_tx_size_bytes_total{cluster=~\"$cluster\"}[$__rate_interval]\n)\n",
     "legendFormat": "{{name}} RX"
    }
   ]
  }
 ]
}