// Copyright The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package collector

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"strings"
	"testing"

	"github.com/prometheus/client_golang/prometheus/testutil"
	"github.com/prometheus/common/promslog"
)

// withQueryAllNodes temporarily overrides the package-level QueryAllNodes
// flag (normally set from --es.all) for the duration of a test.
func withQueryAllNodes(t *testing.T, value bool) {
	t.Helper()
	previous := QueryAllNodes
	QueryAllNodes = value
	t.Cleanup(func() { QueryAllNodes = previous })
}

func TestSSLCertificatesConnectedNodeOnly(t *testing.T) {
	// Default behaviour (--es.all not set): the collector must query
	// /_ssl/certificates exactly once, directly on the connected node, and
	// must never call /_nodes/http. This is what keeps per-node exporter
	// deployments at O(1) certificate calls per scrape instead of O(n).
	withQueryAllNodes(t, false)

	fixture, err := os.ReadFile("../fixtures/ssl/8.9.0.json")
	if err != nil {
		t.Fatal(err)
	}

	certificateRequests := 0
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_ssl/certificates":
			certificateRequests++
			_, _ = w.Write(fixture)
		default:
			t.Errorf("unexpected request path: %s", r.URL.Path)
		}
	}))
	defer ts.Close()

	u, err := url.Parse(ts.URL)
	if err != nil {
		t.Fatal(err)
	}

	c, err := NewSSLCertificates(promslog.NewNopLogger(), u, http.DefaultClient)
	if err != nil {
		t.Fatal(err)
	}

	want := `# HELP elasticsearch_ssl_certificate_expiry_timestamp_seconds Expiry timestamp of an Elasticsearch SSL certificate in Unix time.
# TYPE elasticsearch_ssl_certificate_expiry_timestamp_seconds gauge
elasticsearch_ssl_certificate_expiry_timestamp_seconds{alias="instance",format="PKCS12",name="",node="",path="certs/elastic-certificates.p12",serial_number="a20f0ee901e8f69dc633ff633e5cd5437cdb4137",subject_dn="CN=Elastic Certificate Tool Autogenerated CA"} 1.610743369e+09
elasticsearch_ssl_certificate_expiry_timestamp_seconds{alias="instance",format="PKCS12",name="",node="",path="certs/elastic-certificates.p12",serial_number="fc1905e1494dc5230218d079c47a617088f84ce0",subject_dn="CN=instance"} 1.610743472e+09
`
	if err := testutil.CollectAndCompare(wrapCollector{c}, strings.NewReader(want)); err != nil {
		t.Fatal(err)
	}
	if certificateRequests != 1 {
		t.Fatalf("expected exactly one /_ssl/certificates request, got %d", certificateRequests)
	}
}

func TestSSLCertificatesAllNodes(t *testing.T) {
	// --es.all set: the collector discovers every node via /_nodes/http and
	// queries /_ssl/certificates directly on each one.
	withQueryAllNodes(t, true)

	fixture, err := os.ReadFile("../fixtures/ssl/8.9.0.json")
	if err != nil {
		t.Fatal(err)
	}

	nodeBRequests := 0
	nodeB := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/_ssl/certificates" {
			t.Errorf("unexpected node B request path: %s", r.URL.Path)
		}
		nodeBRequests++
		_, _ = w.Write(fixture)
	}))
	defer nodeB.Close()

	coordinatorCertificatesRequests := 0
	var coordinator *httptest.Server
	coordinator = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/_nodes/http":
			// node-a is reported in the "hostname/ip:port" form Elasticsearch
			// uses when the publish host is a resolvable name; node-b uses
			// the plain "ip:port" form. Both must resolve correctly.
			_, _ = fmt.Fprintf(w, `{"nodes":{"node-a-id":{"name":"node-a","http":{"publish_address":"node-a.internal/%s"}},"node-b-id":{"name":"node-b","http":{"publish_address":%q}}}}`, coordinator.Listener.Addr().String(), nodeB.Listener.Addr().String())
		case "/_ssl/certificates":
			coordinatorCertificatesRequests++
			_, _ = w.Write(fixture)
		default:
			t.Errorf("unexpected coordinator request path: %s", r.URL.Path)
		}
	}))
	defer coordinator.Close()

	u, err := url.Parse(coordinator.URL)
	if err != nil {
		t.Fatal(err)
	}

	c, err := NewSSLCertificates(promslog.NewNopLogger(), u, http.DefaultClient)
	if err != nil {
		t.Fatal(err)
	}

	want := `# HELP elasticsearch_ssl_certificate_expiry_timestamp_seconds Expiry timestamp of an Elasticsearch SSL certificate in Unix time.
# TYPE elasticsearch_ssl_certificate_expiry_timestamp_seconds gauge
elasticsearch_ssl_certificate_expiry_timestamp_seconds{alias="instance",format="PKCS12",name="node-a",node="node-a-id",path="certs/elastic-certificates.p12",serial_number="a20f0ee901e8f69dc633ff633e5cd5437cdb4137",subject_dn="CN=Elastic Certificate Tool Autogenerated CA"} 1.610743369e+09
elasticsearch_ssl_certificate_expiry_timestamp_seconds{alias="instance",format="PKCS12",name="node-a",node="node-a-id",path="certs/elastic-certificates.p12",serial_number="fc1905e1494dc5230218d079c47a617088f84ce0",subject_dn="CN=instance"} 1.610743472e+09
elasticsearch_ssl_certificate_expiry_timestamp_seconds{alias="instance",format="PKCS12",name="node-b",node="node-b-id",path="certs/elastic-certificates.p12",serial_number="a20f0ee901e8f69dc633ff633e5cd5437cdb4137",subject_dn="CN=Elastic Certificate Tool Autogenerated CA"} 1.610743369e+09
elasticsearch_ssl_certificate_expiry_timestamp_seconds{alias="instance",format="PKCS12",name="node-b",node="node-b-id",path="certs/elastic-certificates.p12",serial_number="fc1905e1494dc5230218d079c47a617088f84ce0",subject_dn="CN=instance"} 1.610743472e+09
`
	if err := testutil.CollectAndCompare(wrapCollector{c}, strings.NewReader(want)); err != nil {
		t.Fatal(err)
	}
	if coordinatorCertificatesRequests != 1 {
		t.Fatalf("expected one coordinator certificate request, got %d", coordinatorCertificatesRequests)
	}
	if nodeBRequests != 1 {
		t.Fatalf("expected one node B certificate request, got %d", nodeBRequests)
	}
}

func TestSSLCertificatesURLHostnamePrefix(t *testing.T) {
	base, err := url.Parse("https://coordinator.example.com:9200")
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name           string
		publishAddress string
		wantHost       string
	}{
		{
			name:           "bare ip and port",
			publishAddress: "10.0.1.5:9200",
			wantHost:       "10.0.1.5:9200",
		},
		{
			name:           "hostname prefixed",
			publishAddress: "es-node-1.internal/10.0.1.5:9200",
			wantHost:       "10.0.1.5:9200",
		},
		{
			name:           "with surrounding whitespace",
			publishAddress: "  10.0.1.5:9200  ",
			wantHost:       "10.0.1.5:9200",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := sslCertificatesURL(base, tt.publishAddress)
			if err != nil {
				t.Fatalf("sslCertificatesURL(%q) returned error: %v", tt.publishAddress, err)
			}
			if got.Host != tt.wantHost {
				t.Fatalf("sslCertificatesURL(%q).Host = %q, want %q", tt.publishAddress, got.Host, tt.wantHost)
			}
			if got.Scheme != base.Scheme {
				t.Fatalf("sslCertificatesURL(%q).Scheme = %q, want %q", tt.publishAddress, got.Scheme, base.Scheme)
			}
			if got.Path != "/_ssl/certificates" {
				t.Fatalf("sslCertificatesURL(%q).Path = %q, want /_ssl/certificates", tt.publishAddress, got.Path)
			}
		})
	}
}
