name: Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_run:
    workflows: [Release]
    types: [completed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  on-success:
    # The type of runner that the job will run on
    runs-on: tools-runner
    steps:
    - name: Trigger jenkins job to upload master to Quay.io
      uses: franco-nonne/jenkins-job-trigger-action@update-bundler
      with:
        jenkins_url: ${{ secrets.JENKINS_INTERNAL_URL }}
        jenkins_user: ${{ secrets.JENKINS_BOT_API_USER }}
        jenkins_token: ${{ secrets.JENKINS_BOT_API_TOKEN }}
        job_timeout: "300"
        job_name: "promcat/job/exporters/job/integrations-elasticsearch-exporter"
        job_params: |
          {
            "DRY_RUN": "false",
            "SCRATCH": "true",
            "EXPORTER": "elasticsearch-exporter"
          }
